//! SeaORM entity definitions.
//!
//! These are auto-generated by `sea-orm-cli generate entity` but
//! we maintain them manually for better control.

pub mod post;
pub mod user;

pub use post::Entity as Post;
pub use user::Entity as User;
